version: '2'


services:
  webapp:
    image: 'yuriynikitenko/expenser:master-SNAPSHOT'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    volumes:
      - /home/admin/data:/data/db
    ports:
      - '27017:27017'
