version: '3.5'


services:
  webapp:
    image: 'yuriynikitenko/expenser:master-SNAPSHOT'
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    volumes:
      - /Users/yuriy/data/backup2019_11_15__04_04_01:/data/db
    ports:
      - '27017:27017'